name: Bug Report
description: Report a bug
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can someone else trigger this?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: OpenCrust version
      placeholder: "e.g. 0.1.0"
    validations:
      required: true
