name: Feature / Implementation Task
description: Track a new feature or component implementation
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for new features, channel implementations, provider integrations, and other development tasks.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be built?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What does "done" look like?
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: OpenClaw Reference
      description: Links to the equivalent OpenClaw TypeScript code, if applicable.
    validations:
      required: false
  - type: dropdown
    id: crate
    attributes:
      label: Target Crate
      options:
        - opencrust-cli
        - opencrust-gateway
        - opencrust-config
        - opencrust-channels
        - opencrust-agents
        - opencrust-db
        - opencrust-plugins
        - opencrust-media
        - opencrust-security
        - opencrust-common
        - multiple / other
    validations:
      required: true
