name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? We'd love to hear it.
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - New channel adapter
        - LLM provider support
        - Agent / tools
        - Memory / search
        - CLI
        - Gateway / API
        - Security
        - Plugins / WASM
        - MCP support
        - Performance
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve? Why do you need it?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or other approaches you've thought about?
    validations:
      required: false
  - type: dropdown
    id: contribute
    attributes:
      label: Would you work on this?
      options:
        - "Yes, I'd like to submit a PR"
        - "I can help test"
        - "No, just suggesting"
    validations:
      required: true
